language: c
notifications:
  email: false
before_install: sudo apt-get install libtinycdb-devel
script: make CC="cc -Wall -O2 -g -I/usr/include" CDBLIB="/usr/lib/libcdb.a"
compiler:
  - clang
  - gcc
install: true
